# 3-15  重要细节处理—全局异常和响应关联

**1. 在 LoadRouter类 追加相应结果。**

```ts
    this.app.context.success = success
    this.app.context.fail = fail
```

**2. 修改全局异常**。

```ts
import Koa, { Context } from 'koa'
const globalException = async (ctx: Context, next: Koa.Next) => {
  const context = ctx.app.context
  console.log('进入中间件异常')
  try {
    await next()
  } catch (err: any) {
    ctx.body = context.fail(`服务器错误${err.message}`)
  }
}

export default globalException
```
